# Generated by Django 5.0.6 on 2026-09-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract_source_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['created_at']},
        ),
    ]
