# Generated by Django 5.0.6 on 2026-09-04 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('discrepant', 'Discrepant'), ('unmatched', 'Unmatched')], default='pending', max_length=20)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='none', max_length=20)),
                ('agent_reasoning', models.TextField(blank=True)),
                ('review_action', models.CharField(blank=True, choices=[('accept', 'Accepted discrepancy'), ('dispute', 'Dispute'), ('false_positive', 'False positive')], max_length=20)),
                ('delivery_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.deliveryreceipt')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_result', to='documents.invoice')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.purchaseorder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status', 'severity'], name='matching_ma_workspa_6c7edd_idx')],
            },
        ),
    ]
