# Generated by Django 5.0.6 on 2026-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='decision_actor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
