events {}

http {
  upstream web_backend { server web:8000; }
  upstream asgi_backend { server asgi:8001; }
  upstream frontend_app { server frontend:80; }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://web_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
      proxy_pass http://web_backend;
      proxy_set_header Host $host;
    }

    location /static/ {
  proxy_pass http://web_backend;
  proxy_set_header Host $host;
   }

    location /webhooks/ {
      proxy_pass http://web_backend;
      proxy_set_header Host $host;
    }

    location /media/ {
      proxy_pass http://web_backend;
    }

    location /ws/ {
      proxy_pass http://asgi_backend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_read_timeout 3600s;
    }

    location / {
      proxy_pass http://frontend_app;
      proxy_set_header Host $host;
    }
  }
}
