"""
Migration: add default ordering (-created_at) to Document model.

Generated by: python manage.py makemigrations documents
Applied by:   python manage.py migrate documents
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_extraction_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
    ]
